"""empty message

Revision ID: 6ad5ae884f36
Revises: 65c98df88eb5
Create Date: 2020-10-16 16:09:13.509174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad5ae884f36'
down_revision = '65c98df88eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('is_seeking', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_desc')
    op.drop_column('artist', 'is_seeking')
    # ### end Alembic commands ###
