"""empty message

Revision ID: 952b3608d69b
Revises: d86cda9cf7b6
Create Date: 2020-10-21 13:36:26.085866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952b3608d69b'
down_revision = 'd86cda9cf7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(), nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
