"""empty message

Revision ID: 978f210856fd
Revises: 6ad5ae884f36
Create Date: 2020-10-17 14:21:02.731226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978f210856fd'
down_revision = '6ad5ae884f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('is_seeking', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_desc', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'seeking_desc')
    op.drop_column('venue', 'is_seeking')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
